---
kind: ImageDigestMirrorSet
apiVersion: config.openshift.io/v1
metadata:
  name: brew
spec:
  imageDigestMirrors:
    - source: registry.redhat.io
      mirrors:
        - brew.registry.redhat.io
        - registry.stage.redhat.io
    - source: registry.stage.redhat.io
      mirrors:
        - brew.registry.redhat.io
    - source: registry-proxy.engineering.redhat.com
      mirrors:
        - brew.registry.redhat.io

