FROM src

LABEL source="cnv-ci/hack/Dockerfile.upgrade.src.ci"

RUN dnf install -y --allowerasing --nodocs --setopt=install_weak_deps=False \
    expect sqlite jq \
    && dnf clean all \
    && rm -rfv \
        /var/cache/dnf \
        /var/lib/dnf \
        /var/log/dnf.* \
        /var/log/hawkey.log \
        /var/cache/ldconfig

COPY oc /usr/bin/oc
