FROM quay.io/centos/centos:stream10

LABEL source="cnv-ci/hack/Dockerfile.test.src.ci"

COPY --from=docker.io/mikefarah/yq /usr/bin/yq /usr/bin/yq

# Install required utils
RUN dnf update -y \
    && dnf install -y --allowerasing --nodocs --setopt=install_weak_deps=False jq curl \
    && dnf clean all \
    && rm -rfv \
        /var/cache/dnf \
        /var/lib/dnf \
        /var/log/dnf.* \
        /var/log/hawkey.log \
        /var/cache/ldconfig \
    && yq --version
