FROM src

# Install required utils
RUN dnf update -y \
    && dnf install -y jq curl \
    && dnf clean all \
    && rm -rfv \
        /var/cache/dnf \
        /var/lib/dnf \
        /var/log/dnf.* \
        /var/log/hawkey.log \
        /var/cache/ldconfig

# Install yq
RUN YQ_LATEST_VERSION=$(curl -fsSL -H 'Accept: application/json' https://github.com/mikefarah/yq/releases/latest | jq -r .tag_name) && \
    curl -fsSLo /usr/bin/yq "https://github.com/mikefarah/yq/releases/download/$YQ_LATEST_VERSION/yq_linux_amd64" && \
    chmod +x /usr/bin/yq
