---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-path-disk-alpine
  labels:
    kubevirt.io: ""
    os: "alpine"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/hostImages/alpine
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-path-disk-custom
  labels:
    kubevirt.io: ""
    os: "custom"
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/hostImages/custom
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: disks-images-provider
  namespace: openshift-cnv
  labels:
    kubevirt.io: "disks-images-provider"
spec:
  selector:
    matchLabels:
      kubevirt.io: "disks-images-provider"
  template:
    metadata:
      labels:
        name: disks-images-provider
        kubevirt.io: disks-images-provider
      name: disks-images-provider
    spec:
      serviceAccountName: kubevirt-testing
      containers:
        - name: target
          image: quay.io/kubevirt/disks-images-provider:v1.6.0-beta.0
          imagePullPolicy: Always
          env:
            - name: NUM_TEST_IMAGE_REPLICAS
              value: "8"
          volumeMounts:
          - name: images
            mountPath: /hostImages
          - name: local-storage
            mountPath: /local-storage
          - name: host-dir
            mountPath: /host
            mountPropagation: Bidirectional
          securityContext:
            privileged: true
            readOnlyRootFilesystem: false
          readinessProbe:
            exec:
              command:
              - cat
              - /ready
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: images
          hostPath:
            path: /tmp/hostImages
            type: DirectoryOrCreate
        - name: local-storage
          hostPath:
            path: /mnt/local-storage
            type: DirectoryOrCreate
        - name: host-dir
          hostPath:
            path: /
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-block-storage-cirros
  labels:
    kubevirt.io: ""
    blockstorage: "cirros"
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  local:
    path: /mnt/local-storage/cirros-block-device
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node01
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-block
  volumeMode: Block
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubevirt-testing
  namespace: openshift-cnv
  labels:
    kubevirt.io: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevirt-testing-cluster-admin
  labels:
    kubevirt.io: ""
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: kubevirt-testing
    namespace: openshift-cnv
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kubevirt-test-config
  namespace: openshift-cnv
data:
  test-config.json: |
    {
     "storageClassLocal": "hostpath-provisioner",
     "storageClassHostPath": "hostpath-provisioner",
     "storageClassRhel": "hostpath-provisioner",
     "storageClassWindows": "hostpath-provisioner",
     "manageStorageClasses": false
    }
