name: CNV Informing Jobs Slack Reporter

on:
  schedule:
    - cron: '30 6 * * *'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./automation/slack-reporter

jobs:
  build-and-run-slack-bot:
    name: CNV Informing Jobs Slack Reporter
    if: github.repository == 'openshift-cnv/cnv-ci'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./automation/slack-reporter/go.mod

      - name: Build
        run: go build -v .

      - name: run
        env:
          HCO_CHANNEL_ID: ${{ secrets.HCO_SLACK_CHANNEL_ID }}
          HCO_GROUP_ID: ${{ secrets.HCO_SLACK_GROUP_ID }}
          HCO_REPORTER_SLACK_TOKEN: ${{ secrets.HCO_REPORTER_SLACK_TOKEN }}
        run:
          ./slack-reporter
